# Generated by Django 5.0.6 on 2024-08-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
