# Generated by Django 5.0.6 on 2024-08-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user',
            new_name='user_email',
        ),
    ]
