# Generated by Django 5.0.6 on 2024-08-02 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_user_passwordreset_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user_email',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
