# Generated by Django 5.0.6 on 2024-08-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_event_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starter',
            fields=[
                ('starter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starter_type', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], default='Veg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StarterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='starters/')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.starter')),
            ],
        ),
    ]
