# Generated by Django 5.0.6 on 2024-08-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_maincourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincourse',
            name='images',
        ),
        migrations.CreateModel(
            name='MainCourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_courses/')),
                ('main_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.maincourse')),
            ],
        ),
    ]
