# Generated by Django 5.0.6 on 2024-08-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_dessertimage_dessert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
