# Generated by Django 5.0.6 on 2024-08-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.religion'),
        ),
        migrations.AddField(
            model_name='starter',
            name='Event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starters', to='store.event'),
        ),
        migrations.AddField(
            model_name='starter',
            name='package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starters', to='store.package'),
        ),
    ]
