# Generated by Django 5.0.6 on 2024-08-21 08:26

import django.db.models.deletion
from django.db import migrations, models

def create_default_package(apps, schema_editor):
       Package = apps.get_model('store', 'Package')
       if not Package.objects.filter(package_id=1).exists():
           Package.objects.create(package_id=1, name="Default Package", price=0)
class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_starter_event_id'),
    ]

    operations = [
         migrations.RunPython(create_default_package),
        migrations.AddField(
            model_name='occasion',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.package'),
        ),
        migrations.AlterField(
            model_name='occasionimage',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.occasion'),
        ),
    ]

