# Generated by Django 5.0.6 on 2024-08-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_occasion_package_alter_occasionimage_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='package',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='store.package'),
        ),
    ]
