# Generated by Django 5.0.6 on 2024-08-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_occasion_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occasion',
            name='package',
        ),
    ]
