# Generated by Django 5.0.6 on 2024-08-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_occasion_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.package'),
        ),
    ]
