# Generated by Django 5.0.6 on 2024-09-04 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_occasion_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occasionimage',
            name='occasion',
        ),
        migrations.CreateModel(
            name='BookedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('bride_name', models.CharField(max_length=255)),
                ('groom_name', models.CharField(max_length=255)),
                ('guest_count', models.PositiveIntegerField()),
                ('wedding_dates', models.CharField(max_length=255)),
                ('venue_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Occasion',
        ),
        migrations.DeleteModel(
            name='OccasionImage',
        ),
    ]
